/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./model6.glb
Author: Don42 (https://sketchfab.com/Don42)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-x-34-landspeeder-free-3adfdc41c67f4731910800404ba97b4e
Title: Star Wars X-34 Landspeeder [FREE]
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model6(props: any) {
  const { nodes, materials }: any = useGLTF("/model6.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["X-34_metall_0"].geometry}
          material={materials.metall}
        />
        <mesh
          geometry={nodes["X-34_Air_vents_0"].geometry}
          material={materials.Air_vents}
        />
        <mesh
          geometry={nodes["X-34_glass_0"].geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes["X-34_Main_0"].geometry}
          material={materials.Main}
        />
        <mesh
          geometry={nodes["X-34_Color_0"].geometry}
          material={materials.Color}
        />
        <mesh
          geometry={nodes["X-34_Cockpit_0"].geometry}
          material={materials.Cockpit}
        />
        <mesh
          geometry={nodes["X-34_Consoles_0"].geometry}
          material={materials.Consoles}
        />
        <mesh
          geometry={nodes["X-34_Seats_0"].geometry}
          material={materials.Seats}
        />
        <mesh
          geometry={nodes["X-34_Lever_and_button_0"].geometry}
          material={materials.Lever_and_button}
        />
        <mesh
          geometry={nodes["X-34_console_stuff_0"].geometry}
          material={materials.console_stuff}
        />
        <mesh
          geometry={nodes["X-34_Glow_buttons003_0"].geometry}
          material={materials["Glow_buttons.003"]}
        />
        <mesh
          geometry={nodes["X-34_Glow_buttons002_0"].geometry}
          material={materials["Glow_buttons.002"]}
        />
        <mesh
          geometry={nodes["X-34_Glow_buttons_0"].geometry}
          material={materials.Glow_buttons}
        />
        <mesh
          geometry={nodes["X-34_Glow_buttons001_0"].geometry}
          material={materials["Glow_buttons.001"]}
        />
        <mesh
          geometry={nodes["X-34_Steering_Wheel_0"].geometry}
          material={materials.Steering_Wheel}
        />
      </group>
      <mesh
        geometry={nodes["5000_dummmy_0"].geometry}
        material={materials.dummmy}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/model6.glb");
